/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/worlds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorldsController_list"];
        put?: never;
        post: operations["WorldsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/worlds/{worldId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorldsController_get"];
        put?: never;
        post?: never;
        delete: operations["WorldsController_remove"];
        options?: never;
        head?: never;
        patch: operations["WorldsController_rename"];
        trace?: never;
    };
    "/v1/worlds/{worldId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorldsController_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/worlds/{worldId}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorldsController_retry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/worlds/{worldId}/words/{occurrenceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["WorldsController_removeWord"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/sign-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_signUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_signIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_signOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/send-verification-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_sendVerificationEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_verifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/request-password-reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_resetPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_providers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MeController_me"];
        put?: never;
        post?: never;
        delete: operations["MeController_deleteAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MeController_acceptTerms"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/terms/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["MeController_declineTerms"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["MeController_usage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tutor/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["TutorController_conversation"];
        put?: never;
        post?: never;
        delete: operations["TutorController_clear"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SessionsController_current"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SessionsController_start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["SessionsController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sessions/{sessionId}/questions/{questionId}/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["SessionsController_answer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProgressController_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_check"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        WorldSummaryDto: {
            id: string;
            name: string;
            /** @enum {string} */
            status: "ANALYZING" | "READY" | "FAILED";
            /** @description Why the analysis failed, when it did. */
            failureReason?: string | null;
            /** @description A signed link to the thumbnail, valid for a few minutes (P4). Empty when the photo is gone. */
            thumbnailUrl?: string | null;
            /** @description Words found in this world (FR-013). */
            wordCount: number;
            /** @description Of those, the ones the learner has mastered. */
            masteredCount: number;
            createdAt: string;
        };
        HighlightBoxDto: {
            x: number;
            y: number;
            width: number;
            height: number;
        };
        WorldWordDto: {
            /** @description Identifies this word in this world (FR-026). */
            id: string;
            english: string;
            thaiMeaning: string;
            exampleSentence: string;
            /** @enum {string} */
            cefrLevel: "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
            box: components["schemas"]["HighlightBoxDto"];
            /**
             * @description What the learner has to do with this word to master it.
             * @enum {string}
             */
            mastery: "NEW" | "LEARNING" | "FAMILIAR" | "MASTERED";
        };
        WorldDetailDto: {
            id: string;
            name: string;
            /** @enum {string} */
            status: "ANALYZING" | "READY" | "FAILED";
            /** @description Why the analysis failed, when it did. */
            failureReason?: string | null;
            /** @description A signed link to the thumbnail, valid for a few minutes (P4). Empty when the photo is gone. */
            thumbnailUrl?: string | null;
            /** @description Words found in this world (FR-013). */
            wordCount: number;
            /** @description Of those, the ones the learner has mastered. */
            masteredCount: number;
            createdAt: string;
            /** @description A signed link to the prepared photo (P4). */
            photoUrl?: string | null;
            words: components["schemas"]["WorldWordDto"][];
        };
        ErrorBodyDto: {
            /** @enum {string} */
            code: "BAD_REQUEST" | "VALIDATION_FAILED" | "NOT_SIGNED_IN" | "FORBIDDEN" | "ORIGIN_NOT_ALLOWED" | "NOT_FOUND" | "CONFLICT" | "PAYLOAD_TOO_LARGE" | "UNSUPPORTED_MEDIA_TYPE" | "RATE_LIMITED" | "INTERNAL_ERROR" | "SERVICE_UNAVAILABLE" | "TERMS_NOT_ACCEPTED" | "MESSAGE_TOO_LONG" | "ACCOUNT_SUSPENDED" | "TERMS_PENDING" | "AGE_BELOW_MINIMUM" | "NOT_VERIFIED" | "AI_SUSPENDED" | "OWN_ACCOUNT" | "INVALID_CREDENTIALS" | "INVALID_TOKEN" | "EMAIL_ALREADY_REGISTERED" | "WORLD_LIMIT_REACHED" | "WORLD_NOT_READY" | "RETRY_NOT_AVAILABLE" | "LAST_WORD" | "NOTHING_TO_REVIEW" | "SESSION_CLOSED" | "QUESTION_UNAVAILABLE" | "ACTION_NOT_APPLICABLE" | "PHOTO_TOO_LARGE" | "PHOTO_TYPE_NOT_ALLOWED" | "DAILY_ANALYSIS_LIMIT" | "DAILY_TUTOR_LIMIT" | "AI_PROVIDER_UNAVAILABLE";
            /** @description English, for developers; never shown to learners as is. */
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        ErrorResponseDto: {
            error: components["schemas"]["ErrorBodyDto"];
        };
        WorldStatusDto: {
            /** @enum {string} */
            status: "ANALYZING" | "READY" | "FAILED";
            failureReason?: string | null;
        };
        RenameWorldDto: {
            name: string;
        };
        SignUpDto: {
            /** @description Cannot be a placeholder address (D1). */
            email: string;
            /** @description At least 8 characters (V2). */
            password: string;
            /** @description Display name (V12, V19). */
            name: string;
            /** @description Year of birth; the learner must turn 18 this year (V20). */
            birthYear: number;
            /** @description Must be true: accepting the Terms of Use and Privacy Policy (FR-090). False is answered with TERMS_NOT_ACCEPTED. */
            acceptTerms: boolean;
        };
        SignInDto: {
            email: string;
            password: string;
        };
        AiAccessDto: {
            available: boolean;
            /**
             * @description Why AI features are unavailable, if they are.
             * @enum {string|null}
             */
            reason?: "NOT_VERIFIED" | "AI_SUSPENDED" | null;
        };
        MeResponseDto: {
            /** @description The account ID a learner can quote to LanguZe (FR-108). */
            id: string;
            name: string;
            /** @description Empty for accounts without an email address (D1). */
            email: string | null;
            emailVerified: boolean;
            /** @description Whether photo analysis and the tutor are unlocked (SRS 1.3). */
            verifiedForAi: boolean;
            /** @enum {string} */
            role: "LEARNER" | "ADMIN";
            /** @description False while a provider sign-up has not accepted the Terms (FR-090). */
            termsAccepted: boolean;
            aiAccess: components["schemas"]["AiAccessDto"];
        };
        EmailOnlyDto: {
            email: string;
        };
        AcknowledgementDto: {
            /** @example true */
            ok: boolean;
        };
        VerifyEmailDto: {
            /** @description The token from the verification link. */
            token: string;
        };
        ResetPasswordDto: {
            /** @description The token from the reset link. */
            token: string;
            newPassword: string;
        };
        ProvidersResponseDto: {
            /**
             * @description The providers with credentials configured, in the order to show them.
             * @example [
             *       "google",
             *       "line"
             *     ]
             */
            providers: string[];
        };
        AcceptTermsDto: {
            /** @description Display name, prefilled from the provider profile (V12, V19). */
            name: string;
            /** @description Year of birth; the learner must turn 18 this year (V20). */
            birthYear: number;
        };
        UsageResponseDto: {
            /** @description Photo analyses left today. */
            analysesLeft: number;
            /** @description How many a learner gets each day. */
            analysesLimit: number;
            /** @description Tutor messages left today (FR-071). */
            messagesLeft: number;
            /** @description How many a learner gets each day. */
            messagesLimit: number;
            /** @description When both counts start again, in Bangkok time. */
            resetsAt: string;
        };
        DeleteAccountDto: {
            /**
             * @description Exactly "DELETE". Deletion is permanent, so it is never the result of one stray request (FR-007).
             * @enum {string}
             */
            confirmation: "DELETE";
        };
        TutorMessageDto: {
            id: string;
            /** @enum {string} */
            role: "LEARNER" | "TUTOR";
            content: string;
            createdAt: string;
        };
        TutorConversationDto: {
            messages: components["schemas"]["TutorMessageDto"][];
            /** @description Pass as `before` for older messages; empty at the beginning. */
            nextCursor?: string | null;
        };
        QuestionDto: {
            id: string;
            /** @description Which of the session’s questions this is. */
            position: number;
            /** @description A signed link to the world’s photo (P4). */
            photoUrl?: string | null;
            box: components["schemas"]["HighlightBoxDto"];
        };
        LevelChangeDto: {
            english: string;
            /** @enum {string} */
            level: "LEARNING" | "FAMILIAR" | "MASTERED";
        };
        SessionSummaryDto: {
            answeredCount: number;
            correctCount: number;
            xpEarned: number;
            levelChanges: components["schemas"]["LevelChangeDto"][];
        };
        SessionDto: {
            id: string;
            /** @enum {string} */
            kind: "GAME" | "REVIEW";
            /** @enum {string} */
            status: "IN_PROGRESS" | "COMPLETED" | "ABANDONED";
            /** @description The world being played; empty for a review. */
            worldId?: string | null;
            answeredCount: number;
            questionCount: number;
            /** @description What to ask next; empty when nothing is left to ask. */
            nextQuestion?: components["schemas"]["QuestionDto"] | null;
            startedAt: string;
            /** @description Only for a COMPLETED session. One left unfinished has none (FR-036). */
            summary?: components["schemas"]["SessionSummaryDto"] | null;
        };
        StartSessionDto: {
            /** @enum {string} */
            kind: "GAME" | "REVIEW";
            /**
             * Format: uuid
             * @description The world to play; required for a game only (FR-030).
             */
            worldId?: string;
        };
        AnswerDto: {
            answer?: string;
            /** @description The learner gave up on this word. */
            dontKnow?: boolean;
        };
        WordFeedbackDto: {
            english: string;
            thaiMeaning: string;
            exampleSentence: string;
        };
        MasteryChangeDto: {
            /** @enum {string|null} */
            before?: "LEARNING" | "FAMILIAR" | "MASTERED" | null;
            /** @enum {string} */
            after: "LEARNING" | "FAMILIAR" | "MASTERED";
        };
        AnswerResultDto: {
            correct: boolean;
            dontKnow: boolean;
            /** @description This question was already answered; nothing was recorded again (FR-034). */
            alreadyAnswered: boolean;
            word: components["schemas"]["WordFeedbackDto"];
            xpAwarded: number;
            mastery: components["schemas"]["MasteryChangeDto"];
            sessionCompleted: boolean;
            summary?: components["schemas"]["SessionSummaryDto"] | null;
        };
        MasteryCountsDto: {
            /** @description Never answered. */
            NEW: number;
            LEARNING: number;
            FAMILIAR: number;
            MASTERED: number;
        };
        WorldProgressDto: {
            id: string;
            name: string;
            wordCount: number;
            masteredCount: number;
        };
        ProgressDto: {
            /** @description Only ever rises, whatever is deleted (V4). */
            totalXp: number;
            words: components["schemas"]["MasteryCountsDto"];
            /** @description Every world the learner has, newest first. */
            worlds: components["schemas"]["WorldProgressDto"][];
        };
        HealthResponseDto: {
            /** @enum {string} */
            status: "ok" | "error";
            /** @enum {string} */
            database: "up" | "down";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    WorldsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldSummaryDto"][];
                };
            };
        };
    };
    WorldsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    name: string;
                    /** Format: binary */
                    photo: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldDetailDto"];
                };
            };
            /** @description NOT_VERIFIED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    WorldsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                worldId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldDetailDto"];
                };
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    WorldsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                worldId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorldsController_rename: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                worldId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameWorldDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldDetailDto"];
                };
            };
        };
    };
    WorldsController_status: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                worldId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldStatusDto"];
                };
            };
        };
    };
    WorldsController_retry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                worldId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description RETRY_NOT_AVAILABLE */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    WorldsController_removeWord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                worldId: string;
                occurrenceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description LAST_WORD */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_signUp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignUpDto"];
            };
        };
        responses: {
            /** @description TERMS_NOT_ACCEPTED, VALIDATION_FAILED */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description AGE_BELOW_MINIMUM */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description EMAIL_ALREADY_REGISTERED */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_signIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignInDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponseDto"];
                };
            };
            /** @description INVALID_CREDENTIALS */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description ACCOUNT_SUSPENDED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_signOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_sendVerificationEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailOnlyDto"];
            };
        };
        responses: {
            /** @description Always the same answer (FR-005). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcknowledgementDto"];
                };
            };
        };
    };
    AuthController_verifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmailDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcknowledgementDto"];
                };
            };
            /** @description INVALID_TOKEN */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailOnlyDto"];
            };
        };
        responses: {
            /** @description Always the same answer (FR-005). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcknowledgementDto"];
                };
            };
        };
    };
    AuthController_resetPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResetPasswordDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcknowledgementDto"];
                };
            };
            /** @description INVALID_TOKEN */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    AuthController_providers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProvidersResponseDto"];
                };
            };
        };
    };
    MeController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponseDto"];
                };
            };
            /** @description NOT_SIGNED_IN */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    MeController_deleteAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteAccountDto"];
            };
        };
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description VALIDATION_FAILED when the confirmation is missing or wrong */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    MeController_acceptTerms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptTermsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponseDto"];
                };
            };
            /** @description AGE_BELOW_MINIMUM */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    MeController_declineTerms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    MeController_usage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageResponseDto"];
                };
            };
        };
    };
    TutorController_conversation: {
        parameters: {
            query?: {
                /** @description The oldest message already seen; older ones follow it. */
                before?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TutorConversationDto"];
                };
            };
        };
    };
    TutorController_clear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SessionsController_current: {
        parameters: {
            query: {
                kind: "GAME" | "REVIEW";
                /** @description Required for a game. */
                worldId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"];
                };
            };
            /** @description No session is open. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SessionsController_start: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartSessionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"];
                };
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description WORLD_NOT_READY, or NOTHING_TO_REVIEW (FR-053) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    SessionsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDto"];
                };
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    SessionsController_answer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
                questionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnswerDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnswerResultDto"];
                };
            };
            /** @description NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
            /** @description SESSION_CLOSED or QUESTION_UNAVAILABLE */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
    ProgressController_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressDto"];
                };
            };
        };
    };
    HealthController_check: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponseDto"];
                };
            };
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponseDto"];
                };
            };
        };
    };
}
